export interface MessageContent {
  type: string
  text: string // 必ずstring型
  image?: string
}

export interface Message {
  role: 'user' | 'assistant' | 'system' | 'code'
  content?: string | MessageContent[]
  audio?: string
  id?: string
  timestamp?: string
  isAutoGenerated?: boolean // 自動生成されたメッセージかどうか
}

export const EMOTIONS = [
  'neutral',
  'happy',
  'angry',
  'sad',
  'relaxed',
  'surprised',
] as const
export type EmotionType = (typeof EMOTIONS)[number]

export type Talk = {
  emotion: EmotionType
  message: string
  buffer?: ArrayBuffer
}

export const splitSentence = (text: string): string[] => {
  const splitMessages = text.split(/(?<=[。．！？\n])/g)
  return splitMessages.filter((msg) => msg !== '')
}
