export type MessageRole = 'user' | 'assistant' | 'system';

export type MessageContent = {
  type: 'text';
  text: string;
};

export type Message = {
  role: MessageRole;
  content: MessageContent[];
  isAutoGenerated?: boolean;
  timestamp: string;
};

export type ChatLog = Message[]; 